ALTER TABLE users    ADD COLUMN IF NOT EXISTS date_format TEXT NOT NULL DEFAULT 'dmy_slash';
ALTER TABLE users    ADD COLUMN IF NOT EXISTS time_format TEXT NOT NULL DEFAULT '24h';
ALTER TABLE users    ADD COLUMN IF NOT EXISTS timezone    TEXT NOT NULL DEFAULT 'Europe/London';

ALTER TABLE leagues  ADD COLUMN IF NOT EXISTS date_format TEXT NOT NULL DEFAULT 'dmy_slash';
ALTER TABLE leagues  ADD COLUMN IF NOT EXISTS time_format TEXT NOT NULL DEFAULT '24h';
ALTER TABLE leagues  ADD COLUMN IF NOT EXISTS timezone    TEXT NOT NULL DEFAULT 'Europe/London';

ALTER TABLE clubs    ADD COLUMN IF NOT EXISTS date_format TEXT NOT NULL DEFAULT 'dmy_slash';
ALTER TABLE clubs    ADD COLUMN IF NOT EXISTS time_format TEXT NOT NULL DEFAULT '24h';
ALTER TABLE clubs    ADD COLUMN IF NOT EXISTS timezone    TEXT NOT NULL DEFAULT 'Europe/London';
