ALTER TABLE score_cards ADD COLUMN IF NOT EXISTS location_lat DOUBLE PRECISION NULL;
ALTER TABLE score_cards ADD COLUMN IF NOT EXISTS location_lng DOUBLE PRECISION NULL;

ALTER TABLE pellet_test_sessions ADD COLUMN IF NOT EXISTS location_lat DOUBLE PRECISION NULL;
ALTER TABLE pellet_test_sessions ADD COLUMN IF NOT EXISTS location_lng DOUBLE PRECISION NULL;
